// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Home(Props) {
  var match = React.useState((function () {
          return "game-example";
        }));
  var onChange = match[1];
  var value = match[0];
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Lancer ou rejoindre une partie"), React.createElement("form", {
                  onSubmit: (function (param) {
                      return ReasonReactRouter.push("/" + value);
                    })
                }, React.createElement("label", undefined, "Nom de la partie:"), React.createElement("input", {
                      value: value,
                      onChange: (function ($$event) {
                          var value = $$event.target.value;
                          return Curry._1(onChange, (function (param) {
                                        return value;
                                      }));
                        })
                    }), React.createElement("button", {
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/" + value);
                        })
                    }, "Jouer")));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
