// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Ceci est la page d'accueil"), React.createElement("button", {
                  onClick: (function ($$event) {
                      return ReasonReactRouter.push("/game");
                    })
                }, "Afficher le jeu"));
}

var make = Home;

export {
  make ,
  
}
/* react Not a pure module */
