// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function PageNotExist(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "La page demandée n\'existe pas"), React.createElement("button", {
                  onClick: (function ($$event) {
                      return ReasonReactRouter.push("/");
                    })
                }, "Retour à l\'accueil"));
}

var make = PageNotExist;

export {
  make ,
  
}
/* react Not a pure module */
